GET https://test-render-k45v.onrender.com/api/persons

### POST

POST https://test-render-k45v.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Jorge Marquez",
    "number": "780-774-2222"
}

### DELETE

DELETE https://test-render-k45v.onrender.com/api/persons/2

###